# EmperorVanish Configuration

# Scoreboard settings
scoreboard:
  enabled: true
  update-interval: 20 # ticks (20 ticks = 1 second)

# Staff settings
staff:
  # Players with this permission will be shown in staff list
  permission: "emperorvanish.see"

# Vanish settings
vanish:
  # Hide vanished players from tab list
  hide-from-tab: true
  # Disable interactions while vanished
  disable-interactions: true
  # Hide join/quit messages for vanished players
  hide-messages: true
  # Hide particles and other visual effects
  hide-effects: true
